export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const SCHEDULE_ERROR = "SCHEDULE_ERROR";
export const CLEAR_SCHEDULE_ERROR = "CLEAR_SCHEDULE_ERROR";
export const LOAD_TODAYS_SCHEDULE = "LOAD_TODAYS_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const GET_PSYCH_SCHEDULE_BY_ID = "GET_PSYCH_SCHEDULE_BY_ID";
export const TOTAL_SCHEDULE_EACH_DAY = "TOTAL_SCHEDULE_EACH_DAY";