export const GET_AVATAR = "GET_AvATAR"
export const DISPLAY_AVATAR = "DISPLAY_AVATAR";
export const DOESNT_HAVE_AVATAR = "DOESNT_HAVE_AVATAR";
export const LOAD_ALL_PSYCHS_BASIC_PROFILE = "LOAD_PSYCHS_BASIC_PROFILE";
export const LOAD_PSYCH_BASIC_PROFILE = "LOAD_PSYCH_BASIC_PROFILE"