export const GET_PSYCH_APPOINTMENT = "GET_PSYCH_APPOINTMENT";
export const GET_ALL_PSYCH_APPOINTMENT = "GET_ALL_PSYCH_APPOINTMENT";
export const PSYCH_APPOINTMENT_ERROR = "PSYCH_APPOINTMENT_ERROR";
export const GET_APPOINTED_USERS_PROFILE = "GET_APPOINTED_USERS_PROFILE"