export const ADD_PSYCH_PROFILE = "ADD_PSYCH_PROFILE";
// export const SINGLE_PSYCH_PROFILE = "SINGLE_PSYCH_PROFILE";
export const PSYCH_PROFILE_EROOR = "PSYCH_PROFILE_ERROR";
export const PSYCH_PROFILE_FORM = "SINGLE_PSYCH_FORM";
export const SUBMIT_PSCY_PROFILE_FORM = "SUBMIT_PSCY_PROFILE_FORM";
export const LOAD_PSYCH_PROFILE = "LOAD_PSYCH_PROFILE";

// social
export const ADD_PSYCH_SOCIAL = "ADD_PSYCH_SOCIAL";
export const PSYCH_SOCIAL_EROOR = "PSYCH_SOCIAL_ERROR";
