export const ADD_USER_PROFILE = "ADD_USER_PROFILE";
export const LOAD_USER_PROFILE = "LOAD_USER_PROFILE";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_ALL_USERS_PROFILE = "GET_ALL_USERS_PROFILE";
export const DELETE_USER = "DELETE_USER";