export const SET_ALERT = "ADD_CONTACT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_SUCCESS_PSYCHIATRIST = "REGISTER_SUCCESS_PSYCHIATRIST";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const PSYCHIATRIST_LOADED = "PSYCHIATRIST_LOADED";
export const AUTH_ERROR = "AUTH_ERROR"; 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const PSYCHIATRIST_LOGIN_SUCCESS = "PSYCHIATRIST_LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL"; 
export const LOGOUT = "LOGOUT"; 
export const CLEAR_ERRORS = "CLEAR_ERRORS"; 

// For the Article
export const ADD_ARTICLE = "ADD_ARTICLE";
export const LOAD_ARTICLE = "LOAD_ARTICLE";
export const LOAD_PSYCHIATRIST_ARTICLE = "LOAD_PSYCHIATRIST_ARTICLE";
export const SET_CURRENT = "SET_CURRENT";
export const DELETE_ARTICLE = "REMOVE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const CLEAR_ARTICLE = "CLEAR_ARTICLE";
export const CLEAR_CURRENT = "CLEAR_CURRENT";

// For Rooms
export const CREATE_ROOM = "CREATE_ROOM";
export const LOAD_ROOM = "LOAD_ROOM";
export const GET_ROOM = "LOAD_ROOM";
export const ROOM_ERROR = "ROOM_ERROR"


// trial for profile picture 

export const PROFILE = "PROFILE";
